//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.16 at 10:41:11 AM CEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.webservicesoap.org/payments", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.webservicesoap.payments;
